### ISSUE TITLE
Fix Windows build in Go 1.19

### ISSUE THREAD

**Issue by jpillora** [jpillora/sshd-lite#4]
hey @Fusion, i needed to update deps to get latest Go ssh.

Moving up to Go 1.19 brakes only in windows. could you please check out:
https://github.com/jpillora/sshd-lite/actions/runs/4232344720/jobs/7351964766

Will try to release with 1.17 for now... https://github.com/jpillora/sshd-lite/commit/06b36a6456e8582dcededd1980099e8c98262ddd

**Comment by jpillora** [comment]
No rush, I can comment out the windows builds future releases

**Comment by Fusion** [comment]
OK I'l take a look. I was going to check it today but, no. Today is the day that I stupidly delete my dev VMs!

**Comment by jpillora** [comment]
Haha great timing

**Comment by Fusion** [comment]
As you can see, I created a new pull request. As you can also see, it breaks sshd-lite's CI, which still relies on Go 1.17.
 had to work around a breaking change in Go's internal API between both releases.
Makes sense that 1.17 would not like what I did.
Are you ok with only supporting Go 1.19+ or do you need backward compatibility? (I may be able to figure something out)

**Comment by jpillora** [comment]
hey @Fusion I'm happy to drop pre 1.19 support and go ahead with the windows fix (I am in sudden need to use a windows machine – unfortunately 😁)

**Comment by jpillora** [comment]
Closed in [6e023d9](https://github.com/jpillora/sshd-lite/commit/6e023d9326c25331c972cb6f01bee0489c00d8ee)
