### ISSUE TITLE
DoS: Connecting with netcat will block all further connections

### ISSUE THREAD

**Issue by abbbi** [jpillora/sshd-lite#6]
Opening an connection via netcat will output the ssh banner:

```
  ~ $ echo foo | nc localhost 20000
 SSH-2.0-Go
```

until this connection times out, no other ssh connection can be established, basically blocking the complete server.
It appears you need to wrap ssh.NewServerConn or alike into a goroutine.

**Comment by jpillora** [comment]
Thank you, good catch
